# Site settings
title: Nybergica
email: nybergica777@gmail.com
description: Crunchy beats by Pete!
baseurl: "http://ryan258.github.io/nybergica/" # the subpath of your site, e.g. /blog/
url: "http://yourdomain.com" # the base hostname & protocol for your site

#Social Settings
soundcloud: https://soundcloud.com/nybergica
facebook: https://www.facebook.com/
youtube: https://www.youtube.com/
twitter_username: jekyllrb
github_username:  jekyll

# Build settings
markdown: kramdown
